[package]
name = "capmanatee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9"
clap = "3.1"
chrono = "0.4"
ctrlc = "3.2"
